framework:
    secret: "%env(APP_SECRET)%"

    csrf_protection: true

    session:
        handler_id: session.handler.pdo
        cookie_secure: auto
        cookie_samesite: lax

    # esi: true
    # fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
